POST http://localhost:3000/auth/login
content-type: application/json

{
    "name" : "DFUser1",
    "email": "user1@df.com",
    "password": "DFpassword1!"
}

###
// $2b$08$NWhKaZ7weteIDzo/7IPqyONAQIy/0uPWc3gdM612BH3RACVkyJjrC
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "name" : "DFUser3",
    "email": "user3@df.com",
    "password": "DFpassword3!",
    "role": "1",
    "assignedItems": ["Key", "Rope", "Steve", "Poncho"]
} 

###
GET HTTP://localhost:3000/auth/user/6679920f8c0ddca4c92684b5

###
POST HTTP://localhost:3000/item
content-type: application/json

{
    "name" : "Wizard Hat",
    "description": "A very wizard hat",
    "tagList": ["Item", "Wizardly"]
} 

###
GET HTTP://localhost:3000/auth/usersbyitem/Rope

###
PUT HTTP://localhost:3000/item
content-type: application/json

{
    "name" : "Rope",
    "description": "133 ft of Rope",
    "tagList": ["Item", "Adventurer Supplies", "Long"]
}

###
POST HTTP://localhost:3000/item/useritems
content-type: application/json

{
    "name" : "DFUser3",
    "email": "user3@df.com",
    "password": "DFpassword3!",
    "role": "1",
    "assignedItems": ["Key", "Rope", "Steve", "Poncho"]
}